### ISSUE TITLE
Research Github API

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#92]
what information we can git from Github API, and get a JSON from Github that include:
1. The name of the project.
2. The logo of the project.
3. Number of starts.
4. Type of license.
5. Discretion.
6. Issues, assigned, labels.
7. Contributors.

If Github API if not free, connect OZ, other wise, create a dynamic Json with all that details and add to it the videos and the name of the mentor.

**Comment by urish** [comment]
GitHub API is free, but you need to create a token (otherwise you are very limited in the number of requests). There are several ways to create a token: register a GitHub application, use a GitHub action, or a private account token (I think that's not a good choice for production).

So before starting to work on this, I'd suggest to do some research about the best way to achieve this.

**Comment by EladTal14** [comment]
Hi i would like to take this task, and also if you can specify what exactly do you want to do with the information from Github.

**Comment by InbarDanieli** [comment]
Hey @MichalPorag (:
I would like to take the task
